<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>678ee8e4-ee10-4846-b572-d01efa64c0ec</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="monitoring/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Central.Common.Lib/Central.Common.Lib.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="../Central.ServiceDefaults/Central.ServiceDefaults.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\..\Services\UserService\UserService.Api\UserService.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.Seq" />
  </ItemGroup>

</Project>
