<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkRefenrence Include="Microsoft.AspNetCore.App" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Central.Common.Lib\Central.Common.Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="Serilog.AspNetCore" />
</ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>
</Project>
